import {chromium} from 'playwright';import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://127.0.0.1:5182';assert(new URL(base).hostname==='127.0.0.1');assert(process.env.LOBBY_HOST_PIN,'Set the isolated test lobby PIN');
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-background-timer-throttling','--disable-renderer-backgrounding']});const pages=[],errors=[];
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function boot(hash){const c=await browser.newContext({viewport:{width:1280,height:900}}),p=await c.newPage();pages.push(p);p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/?nolock&noao#'+hash);await p.waitForFunction(()=>window.__game?.state==='menu',null,{timeout:90000});return p;}
async function wait(p,fn,timeout=20000){await p.waitForFunction(fn,null,{timeout});}
async function position(p,x,y,z,yaw=0){await p.evaluate(({x,y,z,yaw})=>{const g=window.__game;g.player.teleport(g.player.pos.clone().set(x,y,z));g.player.yaw=yaw;g.player.pitch=0;g.input.reset();},{x,y,z,yaw});}
try{
 const a=await boot('host');await a.locator('#callsign').fill('SKYLINE HOST');await a.locator('#invite-code').fill(process.env.LOBBY_HOST_PIN);await a.locator('#lobby-join').click();await wait(a,()=>window.__game.online.isHost);
 const invite=await a.evaluate(()=>window.__game.online.inviteKey),b=await boot('invite='+invite);await b.locator('#callsign').fill('SKYLINE GUEST');await b.locator('#lobby-join').click();await Promise.all([a,b].map(p=>wait(p,()=>window.__game.online.remotes.size===1)));
 await b.locator('#lobby-class').click();await b.locator('#class-options [data-weapon="rpg7"]').click();await b.locator('#class-options [data-weapon="m32"]').click();await b.locator('#class-done').click();await b.locator('#lobby-ready').click();await a.locator('#lobby-bots').selectOption('3');await a.locator('#lobby-limit').selectOption('30');await wait(a,()=>[...window.__game.online.peers.values()].some(p=>p.ready));await a.locator('#lobby-start').click();await Promise.all([a,b].map(p=>wait(p,()=>window.__game.state==='playing'&&window.__game.countdown<=0,60000)));await a.evaluate(()=>{window.__game.bots.frozen=true;});
 assert.deepEqual(await b.evaluate(()=>window.__game.gunplay.slots.map(s=>s.def.id)),['rpg7','m32']);
 const equipment=await b.evaluate(async()=>{const{WEAPONS,PRIMARY_WEAPONS,SECONDARY_WEAPONS}=await import('/src/game/WeaponDefs.ts');return{unique:new Set(Object.values(WEAPONS).map(w=>w.model.url)).size,total:Object.keys(WEAPONS).length,ratio:WEAPONS.mp5.speedMul/WEAPONS.intervention.speedMul,all:PRIMARY_WEAPONS.length+SECONDARY_WEAPONS.length};});assert.equal(equipment.unique,equipment.total);assert.equal(equipment.all,15);assert(Math.abs(equipment.ratio-1.75)<.001);console.log('PASS custom launcher pair equipped on guest, 15 distinct weapons, 1.75x SMG/sniper speed');
 const guestId=await b.evaluate(()=>window.__game.online.id);if(!process.env.MOBILITY_ONLY){
 await position(a,0,.1,132);await position(b,0,.1,145);await delay(600);await a.evaluate(()=>{const g=window.__game;g.launches=0;const launch=g.ordnance.launch.bind(g.ordnance);g.ordnance.launch=(...args)=>{g.launches++;return launch(...args);};});await b.keyboard.press('f',{delay:120});await wait(a,()=>window.__game.launches>0);await wait(a,()=>!window.__game.player.alive,5000);
 assert.equal(await a.evaluate(()=>window.__game.deathReplay.active),false);assert.equal(await a.evaluate(()=>window.__game.deathReplay.watchingDeath),true);await wait(a,()=>window.__game.deathReplay.active,5000);await a.keyboard.press('Enter');await wait(a,()=>!window.__game.deathReplay.active);assert.equal(await a.evaluate(()=>window.__game.audio.replaying),false);console.log('PASS guest rocket deals host-authorized explosion damage; death animation precedes killcam, skip restores sound');
 await wait(a,()=>window.__game.player.alive,10000);
 await b.keyboard.press('l');await b.locator('#class-options [data-weapon="m14"]').click();await b.locator('#class-options [data-weapon="deagle"]').click();await b.locator('#class-done').click();assert.deepEqual(await b.evaluate(()=>window.__game.gunplay.slots.map(s=>s.def.id)),['rpg7','m32']);
 await a.evaluate(id=>{const g=window.__game;g.online.damage(id,g.online.id,200,'body','SCAR-H',g.player.pos);},guestId);await wait(b,()=>!window.__game.player.alive);await wait(b,()=>window.__game.player.alive,12000);assert.deepEqual(await b.evaluate(()=>window.__game.gunplay.slots.map(s=>s.def.id)),['m14','deagle']);assert.equal(await b.evaluate(()=>window.__game.vm.holo.visible),true);console.log('PASS in-match weapon choices queue together and equip atomically on next life with holographic M14');
 await position(a,8.4,.31,5);await position(b,9.6,.31,5);await delay(700);await b.keyboard.press('e');await b.locator('[data-floor="7"]').click();await wait(a,()=>!window.__game.elevator.moving&&window.__game.elevator.state.floor===7,15000);await delay(300);
 for(const p of[a,b])assert(Math.abs(await p.evaluate(()=>window.__game.player.feetY)-29.7)<.2);console.log('PASS guest-selected elevator carries both host and guest to floor 8');
 for(const floor of[6,5,4,3,2,1,0]){await b.keyboard.press('e');await b.locator('[data-floor="'+floor+'"]').click();await b.waitForFunction(floor=>window.__game.elevator.state.floor===floor&&!window.__game.elevator.moving,floor,{timeout:6000});await delay(100);const y=await b.evaluate(()=>window.__game.player.feetY);assert(Math.abs(y-(.3+4.2*floor))<.2,'Lift landing '+(floor+1));}
 console.log('PASS all eight floor selections and landings');}
 await a.evaluate(()=>{const g=window.__game;g.vehicleAttempts=[];const f=g.vehicles.authorize.bind(g.vehicles);g.vehicles.authorize=(...args)=>{const e=g.online.entity(args[0]),v=g.vehicles.list[args[1]];const result=f(...args);g.vehicleAttempts.push({args,result,p:e?.pos.toArray(),v:v?.pos.toArray(),alive:e?.alive,driver:v?.driver});return result;};});
 // Actual left-click on a selected secondary while riding must stay pointed along the chassis, even when the camera orbits.
 await position(b,45,.1,29);await delay(700);await b.keyboard.press('e',{delay:100});await wait(b,()=>window.__game.player.mounted);await b.evaluate(()=>{window.__game.vehicles.orbit=1.7;});await delay(150);const mounted=await b.evaluate(()=>{const g=window.__game,p=g.player;return{forward:p.forward.toArray(),yaw:p.yaw,ammo:g.gunplay.slot.mag};});await b.mouse.down({button:'right'});await delay(150);assert.equal(await b.evaluate(()=>window.__game.player.ads),0);await b.mouse.up({button:'right'});await b.keyboard.press('f',{delay:120});assert.equal(await b.evaluate(()=>window.__game.gunplay.slot.mag),mounted.ammo-1);assert(Math.abs(mounted.forward[0]+Math.sin(mounted.yaw))<.001&&Math.abs(mounted.forward[2]+Math.cos(mounted.yaw))<.001);await b.keyboard.press('e');await wait(b,()=>!window.__game.player.mounted);console.log('PASS vehicle fire consumes ammo, follows vehicle heading and blocks ADS during camera orbit');
 await position(a,-20,.1,134);await position(b,0,.1,140);await delay(300);
 await a.evaluate(id=>{const k=window.__game.killstreaks;for(const n of[3,5,6,7,8,9])k.award(id,n);},guestId);await wait(b,()=>window.__game.killstreaks.mine.chopper);for(const key of['3','6','7','8']){await b.keyboard.press(key);await delay(150);}await wait(a,()=>window.__game.killstreaks.state.sky.length===4);assert.equal(await b.evaluate(()=>window.__game.killstreaks.radar),true);console.log('PASS 3/6/7/8 rewards consume once and produce shared UAV, strike aircraft, helicopter and bomber');
 await a.evaluate(()=>{window.__game.killstreaks.state.sky=[];});await delay(150);await b.keyboard.press('5');await wait(b,()=>window.__game.killstreaks.controlling);await delay(200);const before=await b.evaluate(()=>window.__game.killstreaks.eye.toArray());await b.keyboard.down('w');await b.keyboard.down('Space');await delay(900);await b.keyboard.up('w');await b.keyboard.up('Space');const after=await b.evaluate(()=>window.__game.killstreaks.eye.toArray());assert(Math.hypot(after[0]-before[0],after[2]-before[2])>8);assert(after[1]>before[1]+3);
 await b.mouse.click(640,450,{button:'right'});await wait(a,()=>window.__game.killstreaks.state.copters[0]?.rockets===5);await b.keyboard.press('e');await wait(b,()=>!window.__game.killstreaks.controlling);console.log('PASS guest chopper moves horizontally and vertically on host; rocket inventory and exit replicate');
 // New invites are still required after reset; never touch the real production controller in this test.
 assert.deepEqual(errors,[]);console.log('PASS zero browser errors');await a.evaluate(()=>window.__game.online.endLobby());
}catch(e){console.error(e);for(let i=0;i<pages.length;i++){await pages[i].screenshot({path:'output/skyline-test-'+i+'.png'}).catch(()=>{});console.log(await pages[i].evaluate(()=>{const g=window.__game;return{state:g?.state,phase:g?.online.world.phase,status:document.querySelector('#lobby-status')?.textContent,alive:g?.player.alive,pos:g?.player.pos.toArray(),weapons:g?.gunplay.slots.map(s=>s.def.id),lift:g?.elevator.state,liftOpen:g?.elevator.open,lobby:document.querySelector('#lobby').className,vehicle:g?.vehicles.list[0]&&{p:g.vehicles.list[0].pos.toArray(),driver:g.vehicles.list[0].driver},attempts:g?.vehicleAttempts,errors:document.querySelector('#ld-text')?.textContent};}).catch(()=>null));}process.exitCode=1;}finally{await browser.close();}
